### ISSUE TITLE
Google Chrome recording symbol still on after stopping the recording

### ISSUE THREAD

**Issue by tdeoliveira05** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#1]
`stopSpeechStream() {
    socket.emit('stopGoogleCloudSpeech');
    input.disconnect(processor);
    processor.disconnect(context.destination);
    input, processor, context, AudioContext = null;
}`

that is my stopSpeechStream function (im using react!), now when I run it, the connection shuts off and everything seems to stop, except google chrome still marks the browser tab as 'recording'.

Any ideas why?

**Comment by vin-ni** [comment]
Added an update. 
I forgot to stop the stream.
Could you test if it's working for you? :)
