### ISSUE TITLE
DeprecationWarning: grpc.load

### ISSUE THREAD

**Issue by ithieund** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#10]
After installing the modules and run, I see this error:

DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
events.js:137
      throw er; // Unhandled 'error' event
      ^

**Comment by vin-ni** [comment]
Updated to google cloud speech 2.1.1.
This fixed the issue.
Thanks for the info :)
