### ISSUE TITLE
convertFloat32ToInt16 not working in MS Edge

### ISSUE THREAD

**Issue by Rhincodon** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#12]
Hi. In `convertFloat32ToInt16` function is used code `(new Int16Array(l / 3);)` where `l` is equals to 2048. So it results to `new Int16Array(682,666666667)`, and that is not correct expression, because array length is float. Somehow only MS Edge see and throw the error

In addition in this code used magic number `3`, I assume it is a result of `44100 / 16000 = 2.75 ~ 3`?

**Comment by Rhincodon** [comment]
> Thanks for the info. I copied this function from another example. Could you give an example on how the function would look correctly?
> 
> ```js
> var left = convertFloat32ToInt16(left)
> 
> function convertFloat32ToInt16(buffer) {
> 	let l = buffer.length;
> 	let buf = new Int16Array(l / 3);
> 
> 	while (l--) {
> 		if (l % 3 == 0) {
> 			buf[l / 3] = buffer[l] * 0xFFFF;
> 		}
> 	}
> 	return buf.buffer
> }
> ```

In my code I use this downsampling function https://stackoverflow.com/questions/28227380/downsampling-a-pcm-audio-buffer-in-javascript

`downsampleBuffer(left, 44100, 16000))`

**Comment by vin-ni** [comment]
I'll implement that!
