### ISSUE TITLE
First call take a while

### ISSUE THREAD

**Issue by notiles** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#14]
Hello !

First, thanks a lot for this work, it save my day ! 

I got a long delay for the first api call, I think that it's a setup from Google, used to reduce server usage but do you have the same issue and any fix ?

Thanks a lot,

**Comment by notiles** [comment]
If i don't use the app (me or any other user) during more that 3 to 5 minutes, it's like I have to authenticate again.

The event binaryData is fired, I checked the value of recognizeStream !== null and it's true, so recognizeStream.write(data) is executed but the Transcription log (and client.emit) are fired around 15 secondes later. 

If you try again it's immediate, and if any other user try it's also immediate. but if you wait again 3 to 5 minutes before a new transcription you have to wait 15 secondes before a Google Response.

**Comment by notiles** [comment]
Are you hosting it on a Google server ? Perhaps it's due to a bad server configuration form my side...

**Comment by vin-ni** [comment]
This is weird. Never happened to me. What if you run it locally?
I've run it successfully locally, on a digital ocean server and on heroku.
Where are you hosting?

**Comment by notiles** [comment]
on digitalocean ... like you

**Comment by notiles** [comment]
I disable IPV6 on server (because I want to install gcloud on server and gcloud is not compatible with IPV6) and it work perfectly now ! I check agin in 15 minutes and tell you.

**Comment by notiles** [comment]
it work like a charm, so IPV6 have to be disable for google cloud ... good to know

(In the same time I installed gcloud on the server and init it with my credentials so I don't know if it could have an incidence...) Again thanks for this repo !

**Comment by vin-ni** [comment]
Amazing! 
I'll add this to the readme.
Don't hesitate sending me what you built with it. Unfortunately I can't really track where it is in use.

**Comment by notiles** [comment]
it's a prototype for a client so I can't show you for now, but I will if we push it to prod a day ...
