### ISSUE TITLE
Running client script on angular

### ISSUE THREAD

**Issue by Linkmetal** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#15]
Hi!

I was integrating your example in an Angular app and I'm having troubles with the AudioContext part. When I run the app I'm getting an execution error that says "AudioContext is not a constructor", I've been researching for some days and I don't figure out how to fix it.

Also, I don't understand what the AudioContext does, so I don't know if there is another way to give the audio stream to the websocket.

Is there a way to skip that AudioContext part or can you explain why you use it there to understand it better?

Best regards

**Comment by vin-ni** [comment]
Didn't have time to look at it yet. Did you figure it out?

**Comment by Linkmetal** [comment]
Yeah, It was a problem with the definition file of the Web Audio Api,, I replaced the index.d.ts on @types/WebAudio for file "WebAudio.d.ts on this repo [https://github.com/Tonejs/TypeScript](url). But I don't know why I didn't have to do that in another version of the project. I don't really know what happened but if there is problems with AudioContext not being defined or something like that, this method would fix it.
