### ISSUE TITLE
Running on mobile (mic almost dont work)

### ISSUE THREAD

**Issue by dsrocha01** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#19]
Hi, i using this node project to stream microphone audio to node app, in Chrome/Firefox PC (Windows 7) work nice ! I Successfull transcrible audio from mic to node and got all speech to text.

But when i try to access app in a Mobile Version (Android Chrome/Firefox) i got problems to use, the words just badly cought and works bad.

U know something about this issue  ? have problems to run this app in mobile browsers versions ?

Tyvm.

**Comment by vin-ni** [comment]
Hi @dsrocha01 ,
I haven't had any problems with mobile phones for now.

Don't hesitate to post any updates you find. 
Thanks!
