### ISSUE TITLE
Error 13?

### ISSUE THREAD

**Issue by lesliepound** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#22]
After no usage on app for awhile I get the following error:

`  [ERROR] Streaming:Error: 13 INTERNAL: `

I am catching it with 

 ```
 recognizeStream = speechClient.streamingRecognize(request)
...
            .on('error', function (e) {
                client.emit('redirectToLogin')
                console.log("\n[ERROR] Streaming:" + e);
                stopRecognitionStream();
            })

```
However it still it crashes. with continual 

`[ERROR] Streaming:Error: Cannot call write after a stream was destroyed`

**Comment by vin-ni** [comment]
Are you opening a new stream? Does the client continue sending data although the stream is closed?

**Comment by lesliepound** [comment]
I don't see how it restarting the stream.

Here's a longer readout. And yes it appears to restart the stream.

[INFO] Query Sent:
[DEBUG] stopping ...
Client Connected to server
Client Connected to server
Client Connected to server
Client Connected to server
Client Connected to server
Client Connected to server
Deserialize user called.===>>>> { familyName: 'removed', givenName: 'removed' }
Deserialize user called.===>>>> { familyName: 'removed', givenName: 'removed' }
streaming; 

[ERROR] Streaming:Error: 13 INTERNAL: 
[DEBUG] stopping ...

[ERROR] Streaming:Error: Cannot call write after a stream was destroyed
[DEBUG] stopping ...
...

**Comment by vin-ni** [comment]
You can take a look here at the restarting: https://github.com/vin-ni/Google-Cloud-Speech-Node-Socket-Playground/blob/79d0d2cb3ba0cad1e94b9f2e8350a3b15ce74f7b/srcLogOnly/app.js#L78-L84
