### ISSUE TITLE
running the stripped down version and getting error

### ISSUE THREAD

**Issue by justinriddiough** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#26]
![image](https://user-images.githubusercontent.com/654993/158274040-84938196-9e06-4c39-b621-aaf9acfd0243.png)

Clicking record makes this error.

**Comment by vin-ni** [comment]
do you have an idea why recordingStatus is null?

**Comment by justinriddiough** [comment]
Hmm, What I did is cut out the lines that referenced recordingStatus, it doesn't exist anywhere in the index.ejs. It started working a bit more. Still some errors but I see the responses in the console now.
