### ISSUE TITLE
How  to config .env to run on server

### ISSUE THREAD

**Issue by apoorvabhavya** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#6]
Hello,
 we have successfully ran on local but we are unable to run this on server can please provide more information on how to config .env.

**Comment by vin-ni** [comment]
Well, you need to open one port on your server and then set the config to the port you opened.

**Comment by apoorvabhavya** [comment]
I had tried as u mentioned but I am getting error like 
"Uncaught (in promise) DOMException: Only secure origins are allowed "

**Comment by vin-ni** [comment]
oh, yes you need ssl on your website.
The browser doesn't allow microphone access without a secure connection.

**Comment by apoorvabhavya** [comment]
can you provide how to get ssl certificate esaily.thanks for quick reply

**Comment by vin-ni** [comment]
This depends on your hoster. Where are you getting your domain / server from? Often you can get it from your hoster. Otherwise check  https://www.openssl.org/

**Comment by apoorvabhavya** [comment]
Hey Even after SSL certificate I am getting same error. I cross checked What I can do. but I am unable to run.

"Uncaught (in promise) DOMException: Only secure origins are allowed "

**Comment by vin-ni** [comment]
Can you share the link to your website?

**Comment by apoorvabhavya** [comment]
We are not using in website. we are trying in localhost xampp. we are using same port as 1337. However we are new to node.js. Hence we are running same programs of yours.

**Comment by vin-ni** [comment]
Hmm, so there must be a xampp setting you are missing. So the website is served but the speech rec is not working, right? Can you send a screenshot of the error log?

**Comment by apoorvabhavya** [comment]
![image](https://user-images.githubusercontent.com/40597068/42360332-de623618-8105-11e8-845f-3529e5e47a3c.png)

**Comment by apoorvabhavya** [comment]
This is the error we are getting

**Comment by vin-ni** [comment]
Did it work out for you? Otherwise i'll close the issue :)
