### ISSUE TITLE
bad language code error

### ISSUE THREAD

**Issue by rrrepos** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#8]
I have used the code exactly as specified in the source however I get the error

````
  error: 
   { details: [],
     code: 3,
     message: 'Invalid recognition \'config\': bad language code.' },
  speechEventType: 'SPEECH_EVENT_UNSPECIFIED' }
````
What would I be setting wrong? Thanks

**Comment by rrrepos** [comment]
oops. your project works. must be something I am doing wrong. will figure out. thanks for this repo

**Comment by vin-ni** [comment]
You're very welcome :) 
Tell me what's wrong once you figure it out. Maybe I can improve the readme

**Comment by rrrepos** [comment]
I stand corrected. Even `2.0.0` seems to give the above error. Only `1.5.0` seems to work well.
